# To execute this docker-compose yml file use docker-compose -f <file_name> up
# Add the "-d" flag at the end for deattached execution
version: "3.5"
services:
  selenium-hub:
    image: selenium/hub:3.13.0-argon
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      qa_network:
        ipv4_address: 172.18.0.2
  chrome:
    image: selenium/node-chrome:3.13.0-argon
    container_name: chrome-node
    ports:
      - "5901:5900"
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      qa_network:
        ipv4_address: 172.18.0.3
  firefox:
    image: selenium/node-firefox:3.13.0-argon
    container_name: firefox-node
    ports:
      - "5902:5900"
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      qa_network:
        ipv4_address: 172.18.0.4
     
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports: 
      - "8080:8080"
    networks:
      qa_network:
        ipv4_address: 172.18.0.5
    volumes:
      - type: bind
        source: ./Shared_Folder/jenkins
        target: /var/jenkins_home/jenkins_bakup
 
networks:
    qa_network:
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16

 



 
